Add Basic UI
chukwuemeka1234/school_library pull request #4
Opened 2022-03-17 21:29 UTC by chukwuemeka1234

**Hi there** 👋 

- [ ] In this PR I added the basic console to the ruby project

2022-03-17 21:54 UTC, MahmoudBakr23 requested changes
Hello @chukwuemeka1234 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Professional README

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 21:54 UTC, MahmoudBakr23 commented on app.rb
> +  end
- [ ] Please make sure to move those 2 methods to the `main.rb` file in order to separate the UI handling from the data/logic extracting. 🙏

2022-03-17 21:54 UTC, MahmoudBakr23 commented on app.rb
> +# rubocop:enable Metrics/ClassLength
- [ ] Please work on the `Rubocop` errors manually instead of disabling the linters for best practices to write cleaner code. 🙏

2022-03-17 21:54 UTC, MahmoudBakr23 commented on app.rb
> +require './students'
- [ ] Please change the file name to `./student` instead of `./students`!

2022-03-18 20:23 UTC, mmsesay approved these changes
Hi @chukwuemeka1234, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 20:23 UTC, mmsesay commented on main.rb
> +main
- [OPTIONAL] I got an error when I tried running the application. Maybe it works well on your side as well as the previous reviewer. But it doesn't even run on my side.

Can you please take a look at it?
It seems the error is coming from the student file.



See screenshot|
:--------------------------:| 
![a1](https://user-images.githubusercontent.com/39523312/159076596-8b2d0a52-6307-4b4b-b8b9-85baf7f6b787.png)

2022-03-19 08:42 UTC, merged